name: Build Rememory

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish --configuration Release --output ./release --no-build
    
    - name: Create ZIP
      run: Compress-Archive -Path ./release/* -DestinationPath Rememory-Setup.zip
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Rememory-Setup
        path: Rememory-Setup.zip
