name: Build Rememory

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore NuGet packages
      run: nuget restore Rememory.sln
    
    - name: Build Solution
      run: msbuild Rememory.sln /p:Configuration=Release /p:Platform="Any CPU"
    
    - name: Create ZIP
      run: Compress-Archive -Path ./Rememory/bin/Release/* -DestinationPath Rememory-Setup.zip
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Rememory-Setup
        path: Rememory-Setup.zip
